sudo apt install tesseract-ocr
sudo apt install libtesseract-dev
# pacote em português
sudo apt-get install tesseract-ocr-por
# pacote em japonês
sudo apt-get install tesseract-ocr-jpn
# pacote em japonês
sudo apt-get install tesseract-ocr-kor
sudo pip3 install pytesseract
sudo pip install pytesseract
